# Generated by Django 2.0.3 on 2018-04-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20180330_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='fav_nums',
            new_name='fac_nums',
        ),
    ]
