# Generated by Django 2.0.3 on 2018-04-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180329_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fav_nums',
            new_name='fac_nums',
        ),
    ]
