# Generated by Django 2.0.3 on 2018-04-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180404_1835'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='course',
    #         old_name='fac_nums',
    #         new_name='fav_nums',
    #     ),
    # ]
